### PR TITLE
Ack, sorry I forgot this bit!!

### PR DESCRIPTION
**Pull request by PjEdwards**

### CODE REVIEW

**Comment by PjEdwards** [comment]
@GUI I'm not sure if these checks are really failing or if its more in-flight CI changes? Is there something I need to do to move this PR downfield?

**Comment by GUI** [comment]
@PjEdwards: Ah, yeah, sorry, I meant to mention this in the previous PR, but no, I don't think these failures are real. I think it's failing due to forks not having access to secrets defined on the main repo in GitHub Actions. But I'll try to get that fixed so that the CI results of forked PRs are actually useful too, I just hadn't tested forks when setting all this up originally.

**Comment by GUI** [comment]
@PjEdwards: If you pull in the latest from `master`, then future forked PRs I believe should have a passing CI test suite now.

**Comment by PjEdwards** [comment]
Sweet, thanks!

**Pull request merged**
