### PR TITLE
LPS - DOCUMENTED APIs

### PR DESCRIPTION
**Pull request by techbrownbags**
- moved tech summaries documentation to partnering
- added labs, experts and labs documentation
- using shared schemas in partnering/definitions

### CODE REVIEW

**Comment by techbrownbags** [comment]
I have a few groups ready for these docs to be published. Any ETA on when this can be merged? I understand this is pretty low on your priorities but thought I'd let you know its going to be used.

**Comment by GUI** [comment]
@techbrownbags: Sorry for the delay, one thing I've just been mulling over is how this changes the top-level organization for the docs. There's some small layout issues this causes on the home page, but I'm also unsure how much sense "Partnering" would make without context (although, this has always been a tricky one to categorize). I guess one question I had was do you see these LPS APIs and the other [Energy Innovations API](https://developer.nrel.gov/docs/technologies/energy-innovations-v1/) as sort of belonging to the same group? Right now, they're currently under the same category, so I was wondering if we should shift those around as well.

We may also need to setup redirects if you don't want existing links to the old docs (at https://developer.nrel.gov/docs/technologies/lab_innovations/) to break. I can help setup those redirects once we're sure about the new structure and URLs.

**Comment by techbrownbags** [comment]
@GUI no worries and good questions. 

1. Energy Innovations API are going away. We shut down the EI APIs for a while and no one complained.
1. marketing summaries API wasn't really published and will be replaced soon so I don't think we need a re-direct. Honestly, I should probably leave it out until we create it's replacement, technology_summaries, backed by faceted search.
1. I'm going to touch base with our primary to see if he has an opinion

**Comment by techbrownbags** [comment]
Talked to the DOE PI he says move forward with partnering. Let me know if anything else is needed

**Comment by techbrownbags** [comment]
I'm starting to look at this. How can I generate these errors locally?

**Comment by GUI** [comment]
@techbrownbags: Assuming you have Ruby and Node.js setup, you can run these tests via:

```sh
# Install dependencies
bundle
yarn

# Run tests
bundle exec rake lint
```

Give a shout if you run into any issues.

**Comment by techbrownbags** [comment]
i'm able to run lint and resolved some issues but i'm seeing an issues with
using relative paths for $refs
an example in experts/spec.yml. when I use the full path lint passes but
the html page fails.

From this page https://github.com/apigee-127/swagger-tools/issues/227, it
appears relative files are on the spec but not supported by swagger-tools?
I didn't see any other projects trying to reuse definitions.

Let me know what you think, i haven't read into this deeply.

responses:
        200:
          description: Successful request
          schema:
            $ref: "#/definitions/expert_response"
definitions:
  expert_response:
    type: object
    $ref: "../definitions/expert.yml#/expert_response"
  experts_response:
    type: object
    $ref: "../definitions/expert.yml#/experts_response"


API Errors:
 62
 63   #/definitions/expert_response/$ref: Reference could not be resolved:
../definitions/expert.yml#/expert_response
 64   #/definitions/experts_response/$ref: Reference could not be resolved:
../definitions/expert.yml#/experts_response

**Pull request merged**
