### PR TITLE
Updates to Wind Toolkit and DSIRE

### PR DESCRIPTION
**Pull request by jduckworth**
@GUI These are changes to the Wind Toolkit documentation and the DSIRE database documentation reflecting the new services that we rolled out this past week. Feel free to get in touch with @PjEdwards or I if you have any questions.

We are looking to update the documentation as quickly as possible, as these changes are live. Thanks!

### CODE REVIEW

**Comment by GUI** [comment]
@jduckworth: It looks like this documentation is for V2 of the energy incentives API, but it's replacing the documentation for V1. It looks like the windtoolkit API might be similar (the API URL being referenced is different, but the documentation is replacing the old stuff). Is that correct? As long as the old APIs are still around and functioning as-is, I'd prefer to keep those existing documentation pages, and then introduce this updated documentation as new pages.

So maybe for the Incentives API, shift the docs into a new `source/docs/electricity/energy-incentives-v2.md.erb` file and something similar for wind toolkit (but it's not versioned, so I'm not sure how you want to distinguish those endpoints)? Then on the old pages I'd revert the changes and tweak them to mark them as deprecated (assuming you want people to transition to the new APIs). Here's an example of how we've handled deprecated pages in the past: https://github.com/NREL/developer.nrel.gov/blob/master/source/docs/solar/dni.md.erb#L3-L10 (basically, update the summary to include a deprecation notice and a link to the new docs, and then also add `deprecated: true` to the top section--this will force the items to the bottom of the listing pages). We can also do more targeted outreach via e-mail to existing users of the old APIs if you want to try to get them off the older APIs.

Does that make sense? I just don't want the reference documentation for the current APIs to suddenly disappear for anyone currently using them. But let me know if you'd prefer to handle this in any other way.

**Comment by jduckworth** [comment]
Hey Nick,

That all sounds good. I'll make those changes and send another pull request tomorrow when the docs have been updated. As for sending a more targeted email, I'll talk with Dan and see if he already has a plan for that or if he wants to bring you in tot he fold to make that happen.

Thanks,

Jon

**Comment by GUI** [comment]
Sounds good, thanks! And if you want, you can also make further commits to this same branch and this pull request should update. So if that's easier than another branch and separate pull request, you can just give me another ping on here whenever you're ready (but another pull request also works dandily too).

**Comment by jduckworth** [comment]
@GUI I've made the necessary changes to bring the old DSIRE docs back in and deprecate them. The Wind Toolkit docs still overwrite the old ones as per the comments from @PjEdwards . Let me know if you see anything else that needs changing.

**Comment by GUI** [comment]
Sorry for the delay. These should be live now.

**Pull request merged**
